### ISSUE TITLE
Visibility's Unit is Wrong

### ISSUE THREAD

**Issue by surajondev** [surajondev/get-weather#3]
The Unit for visibility is wrong. 
Changed it with the appropriate one.

**Comment by surajondev** [comment]
GO ON.

**Comment by pushkar2112** [comment]
Hey, if it is still available I would like to work on this. Please assign this to me!

**Comment by surajondev** [comment]
Sure. You can work on it.

**Comment by pushkar2112** [comment]
So the current unit is in meters, what should the changed unit be?

**Comment by surajondev** [comment]
Meter is the right unit here. You can find another issue.

**Comment by surajondev** [comment]
You ca
