### ISSUE TITLE
Make the UI responsive and UI Changes.

### ISSUE THREAD

**Issue by ghost** [surajondev/get-weather#8]
I want to change the UI overall, if you're okay with it.  And make the website more responsive.
In responvise mode the font-size is same as website fonts-size.

**Comment by Dev-Sam9** [comment]
Okay will try then, I'll keep this for tomorrow :)

**Comment by ShahrozAhmd** [comment]
Hey, i want to contribute to this repo of yours, kindly assign it to me to get it resolved quickly, Thanks buddy

**Comment by manuel12** [comment]
@surajondev I would like to work on this.

**Comment by surajondev** [comment]
Proceed with it.

**Comment by manuel12** [comment]
@surajondev Made PR: https://github.com/surajondev/get-weather/pull/63
